 import { useState } from 'react';
 import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
 import { Button } from '@/components/ui/button';
 import { Badge } from '@/components/ui/badge';
 import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
 import { Textarea } from '@/components/ui/textarea';
 import { ScrollArea } from '@/components/ui/scroll-area';
 import { mockProjectIdeas } from '@/lib/mockData';
 import { 
   Cpu, 
   Lightbulb, 
   Package, 
   FileCode, 
   Send, 
   Loader2,
   CheckCircle,
   Copy,
   Zap,
   CircuitBoard
 } from 'lucide-react';
 import { toast } from 'sonner';
 
 interface ChatMessage {
   role: 'user' | 'assistant';
   content: string;
 }
 
 interface SelectedProject {
   idea: typeof mockProjectIdeas[0] | null;
   components: string[];
   explanation: string;
   code: string;
 }
 
 export default function Projects() {
   const [step, setStep] = useState(1);
   const [chatInput, setChatInput] = useState('');
   const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
     { role: 'assistant', content: 'Hi! I\'m your Project Studio assistant. Tell me what kind of project you\'d like to build, or describe a problem you want to solve. For example: "I want to build a smart irrigation system" or "Create a project using temperature sensors"' }
   ]);
   const [isLoading, setIsLoading] = useState(false);
   const [selectedProject, setSelectedProject] = useState<SelectedProject>({
     idea: null,
     components: [],
     explanation: '',
     code: '',
   });
 
   const handleSendMessage = async () => {
     if (!chatInput.trim()) return;
 
     const userMessage = chatInput;
     setChatInput('');
     setChatMessages(prev => [...prev, { role: 'user', content: userMessage }]);
     setIsLoading(true);
 
     // Simulate AI response
     setTimeout(() => {
       const randomProject = mockProjectIdeas[Math.floor(Math.random() * mockProjectIdeas.length)];
       setSelectedProject(prev => ({ ...prev, idea: randomProject }));
       
       setChatMessages(prev => [...prev, { 
         role: 'assistant', 
         content: `Great choice! Based on your request, I recommend: **${randomProject.title}**\n\n${randomProject.description}\n\n**Difficulty:** ${randomProject.difficulty}\n**Category:** ${randomProject.category}\n\nWould you like to proceed with this project? Click "Next Step" to continue with component selection.`
       }]);
       setIsLoading(false);
     }, 1500);
   };
 
   const handleComponentSelection = () => {
     if (selectedProject.idea) {
       setSelectedProject(prev => ({
         ...prev,
         components: prev.idea?.components || [],
       }));
       setStep(3);
       
       // Generate explanation
       setTimeout(() => {
         setSelectedProject(prev => ({
           ...prev,
           explanation: `## Working Principle\n\nThe ${prev.idea?.title} works by connecting sensors to the microcontroller which processes the data and controls the output devices.\n\n## Pin Connections\n\n| Component | Pin | Connection |\n|-----------|-----|------------|\n| ${prev.idea?.components[0]} | VCC | 5V |\n| ${prev.idea?.components[0]} | GND | GND |\n| ${prev.idea?.components[0]} | DATA | D2 |\n| ${prev.idea?.components[1] || 'LED'} | IN1 | D3 |\n| ${prev.idea?.components[1] || 'LED'} | IN2 | D4 |\n\n## Circuit Diagram Notes\n\nConnect power supply (5V) to VCC pins. Ensure proper grounding. Use pull-up resistors where necessary.`,
         }));
       }, 1000);
     }
   };
 
   const handleGenerateCode = () => {
     setStep(4);
     setIsLoading(true);
 
     setTimeout(() => {
       const project = selectedProject.idea;
       const code = `/*
  * ${project?.title}
  * Generated by Smart Core Project Studio
  * 
  * Components: ${project?.components.join(', ')}
  */
 
 // Pin definitions
 #define SENSOR_PIN 2
 #define OUTPUT_PIN 3
 #define LED_PIN 13
 
 // Variables
 int sensorValue = 0;
 bool outputState = false;
 
 void setup() {
   // Initialize serial communication
   Serial.begin(9600);
   
   // Configure pins
   pinMode(SENSOR_PIN, INPUT);
   pinMode(OUTPUT_PIN, OUTPUT);
   pinMode(LED_PIN, OUTPUT);
   
   Serial.println("${project?.title} initialized!");
 }
 
 void loop() {
   // Read sensor value
   sensorValue = digitalRead(SENSOR_PIN);
   
   // Process and control output
   if (sensorValue == HIGH) {
     digitalWrite(OUTPUT_PIN, HIGH);
     digitalWrite(LED_PIN, HIGH);
     outputState = true;
   } else {
     digitalWrite(OUTPUT_PIN, LOW);
     digitalWrite(LED_PIN, LOW);
     outputState = false;
   }
   
   // Log to serial monitor
   Serial.print("Sensor: ");
   Serial.print(sensorValue);
   Serial.print(" | Output: ");
   Serial.println(outputState ? "ON" : "OFF");
   
   delay(100);
 }`;
       
       setSelectedProject(prev => ({ ...prev, code }));
       setIsLoading(false);
       toast.success('Code generated successfully!');
     }, 2000);
   };
 
   const copyCode = () => {
     navigator.clipboard.writeText(selectedProject.code);
     toast.success('Code copied to clipboard!');
   };
 
   const steps = [
     { num: 1, title: 'Idea Generation', icon: Lightbulb },
     { num: 2, title: 'Components', icon: Package },
     { num: 3, title: 'Explanation', icon: CircuitBoard },
     { num: 4, title: 'Code', icon: FileCode },
   ];
 
   return (
     <div className="p-6 lg:p-8 max-w-6xl mx-auto">
       <div className="mb-8">
         <h1 className="text-2xl font-bold text-foreground mb-2 flex items-center gap-2">
           <Cpu className="w-6 h-6 text-accent" />
           Smart Core Project Studio
         </h1>
         <p className="text-muted-foreground">
           AI-powered embedded project development from idea to ready-to-upload code
         </p>
       </div>
 
       {/* Stepper */}
       <div className="flex items-center justify-between mb-8 px-4">
         {steps.map((s, i) => (
           <div key={s.num} className="flex items-center">
             <div className={`flex items-center gap-2 ${step >= s.num ? 'text-primary' : 'text-muted-foreground'}`}>
               <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                 step > s.num 
                   ? 'bg-primary text-primary-foreground' 
                   : step === s.num 
                     ? 'bg-primary/20 text-primary border-2 border-primary' 
                     : 'bg-muted text-muted-foreground'
               }`}>
                 {step > s.num ? <CheckCircle className="w-5 h-5" /> : <s.icon className="w-5 h-5" />}
               </div>
               <span className="hidden md:block text-sm font-medium">{s.title}</span>
             </div>
             {i < steps.length - 1 && (
               <div className={`w-12 lg:w-24 h-0.5 mx-2 ${step > s.num ? 'bg-primary' : 'bg-muted'}`} />
             )}
           </div>
         ))}
       </div>
 
       {/* Step Content */}
       <Card>
         <CardContent className="p-6">
           {step === 1 && (
             <div className="space-y-4">
               <CardTitle className="text-lg flex items-center gap-2">
                 <Lightbulb className="w-5 h-5 text-secondary" />
                 Project Idea Generation
               </CardTitle>
               
               <ScrollArea className="h-[300px] border rounded-lg p-4 bg-muted/30">
                 {chatMessages.map((msg, i) => (
                   <div 
                     key={i} 
                     className={`mb-4 ${msg.role === 'user' ? 'text-right' : ''}`}
                   >
                     <div className={`inline-block max-w-[80%] p-3 rounded-lg ${
                       msg.role === 'user' 
                         ? 'bg-primary text-primary-foreground' 
                         : 'bg-muted'
                     }`}>
                       <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                     </div>
                   </div>
                 ))}
                 {isLoading && (
                   <div className="flex items-center gap-2 text-muted-foreground">
                     <Loader2 className="w-4 h-4 animate-spin" />
                     <span className="text-sm">Thinking...</span>
                   </div>
                 )}
               </ScrollArea>
 
               <div className="flex gap-2">
                 <Textarea
                   placeholder="Describe your project idea..."
                   value={chatInput}
                   onChange={(e) => setChatInput(e.target.value)}
                   onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSendMessage()}
                   className="min-h-[60px]"
                 />
                 <Button onClick={handleSendMessage} disabled={isLoading} size="icon" className="h-auto">
                   <Send className="w-4 h-4" />
                 </Button>
               </div>
 
               {selectedProject.idea && (
                 <Button onClick={() => setStep(2)} className="w-full gap-2">
                   Next: Select Components
                   <Zap className="w-4 h-4" />
                 </Button>
               )}
             </div>
           )}
 
           {step === 2 && selectedProject.idea && (
             <div className="space-y-4">
               <CardTitle className="text-lg flex items-center gap-2">
                 <Package className="w-5 h-5 text-secondary" />
                 Component Selection
               </CardTitle>
               <CardDescription>
                 Recommended components for {selectedProject.idea.title}
               </CardDescription>
 
               <div className="grid md:grid-cols-2 gap-4">
                 {selectedProject.idea.components.map((component) => (
                   <Card key={component} className="border-2 border-primary bg-primary/5">
                     <CardContent className="p-4 flex items-center gap-3">
                       <CheckCircle className="w-5 h-5 text-primary" />
                       <span className="font-medium">{component}</span>
                     </CardContent>
                   </Card>
                 ))}
               </div>
 
               <div className="flex gap-3">
                 <Button variant="outline" onClick={() => setStep(1)}>Back</Button>
                 <Button onClick={handleComponentSelection} className="flex-1 gap-2">
                   Next: Project Explanation
                   <Zap className="w-4 h-4" />
                 </Button>
               </div>
             </div>
           )}
 
           {step === 3 && (
             <div className="space-y-4">
               <CardTitle className="text-lg flex items-center gap-2">
                 <CircuitBoard className="w-5 h-5 text-secondary" />
                 Project Explanation & Pin Connections
               </CardTitle>
 
               <ScrollArea className="h-[350px] border rounded-lg p-4 bg-muted/30">
                 <div className="prose prose-sm max-w-none">
                   <pre className="whitespace-pre-wrap font-sans text-sm">
                     {selectedProject.explanation || 'Generating explanation...'}
                   </pre>
                 </div>
               </ScrollArea>
 
               <div className="flex gap-3">
                 <Button variant="outline" onClick={() => setStep(2)}>Back</Button>
                 <Button onClick={handleGenerateCode} className="flex-1 gap-2">
                   Generate Embedded Code
                   <FileCode className="w-4 h-4" />
                 </Button>
               </div>
             </div>
           )}
 
           {step === 4 && (
             <div className="space-y-4">
               <div className="flex items-center justify-between">
                 <CardTitle className="text-lg flex items-center gap-2">
                   <FileCode className="w-5 h-5 text-secondary" />
                   Generated Embedded Code (Arduino/ESP32)
                 </CardTitle>
                 <Button variant="outline" size="sm" onClick={copyCode} className="gap-2">
                   <Copy className="w-4 h-4" />
                   Copy Code
                 </Button>
               </div>
 
               {isLoading ? (
                 <div className="h-[350px] border rounded-lg flex items-center justify-center bg-muted/30">
                   <div className="text-center">
                     <Loader2 className="w-8 h-8 animate-spin text-primary mx-auto mb-2" />
                     <p className="text-muted-foreground">Generating code...</p>
                   </div>
                 </div>
               ) : (
                 <ScrollArea className="h-[350px] border rounded-lg bg-navy-900 p-4">
                   <pre className="text-sm text-teal-300 font-mono whitespace-pre-wrap">
                     {selectedProject.code}
                   </pre>
                 </ScrollArea>
               )}
 
               <div className="flex gap-3">
                 <Button variant="outline" onClick={() => setStep(3)}>Back</Button>
                 <Button 
                   onClick={() => {
                     setStep(1);
                     setSelectedProject({ idea: null, components: [], explanation: '', code: '' });
                     setChatMessages([chatMessages[0]]);
                   }} 
                   className="flex-1 gap-2"
                 >
                   Start New Project
                   <Lightbulb className="w-4 h-4" />
                 </Button>
               </div>
             </div>
           )}
         </CardContent>
       </Card>
     </div>
   );
 }